// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.DataAccess.DbContexts;

namespace WebApp.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20201207224412_AddCoreAndSeed")]
    partial class AddCoreAndSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WebApp.Domain.Core.Petition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Header")
                        .HasColumnType("text");

                    b.Property<long>("NextGoal")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<long>("TotalGoal")
                        .HasColumnType("bigint");

                    b.Property<long>("VotersAmount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Petitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu nislnunc mi ipsum faucibus vitae aliquet nec.",
                            ExpirationDate = new DateTime(2020, 12, 7, 22, 44, 11, 122, DateTimeKind.Utc).AddTicks(1493),
                            Header = "TestPetition",
                            NextGoal = 100L,
                            PublicationDate = new DateTime(2020, 12, 7, 22, 44, 11, 122, DateTimeKind.Utc).AddTicks(490),
                            ShortDescription = "ShortDescription",
                            TotalGoal = 20000L,
                            VotersAmount = 15L
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Core.PetitionUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PetitionId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PetitionId");

                    b.HasIndex("PetitionId");

                    b.ToTable("PetitionUser");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PetitionId = 1
                        },
                        new
                        {
                            UserId = 2,
                            PetitionId = 1
                        },
                        new
                        {
                            UserId = 3,
                            PetitionId = 1
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Core.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<long>("VotersAmount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Polls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu nislnunc mi ipsum faucibus vitae aliquet nec.",
                            Header = "TestPetition",
                            IsAnonymous = false,
                            PublicationDate = new DateTime(2020, 12, 7, 22, 44, 11, 122, DateTimeKind.Utc).AddTicks(3427),
                            ShortDescription = "ShortDescription",
                            VotersAmount = 15L
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Core.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Email = "testuser@mail.ru",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "testUser"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Email = "testuser1@mail.ru",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "testUser1"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Email = "testuser2@mail.ru",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "testUser2"
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Core.VotingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int?>("PollId")
                        .HasColumnType("integer");

                    b.Property<long>("VotersAmount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "1",
                            PollId = 1,
                            VotersAmount = 3L
                        },
                        new
                        {
                            Id = 2,
                            Content = "2",
                            PollId = 1,
                            VotersAmount = 2L
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Core.VotingOptionUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VotingOptionId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "VotingOptionId");

                    b.HasIndex("VotingOptionId");

                    b.ToTable("VotingOptionUser");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            VotingOptionId = 1
                        },
                        new
                        {
                            UserId = 2,
                            VotingOptionId = 1
                        },
                        new
                        {
                            UserId = 3,
                            VotingOptionId = 1
                        },
                        new
                        {
                            UserId = 1,
                            VotingOptionId = 2
                        },
                        new
                        {
                            UserId = 2,
                            VotingOptionId = 2
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Core.Petition", b =>
                {
                    b.HasOne("WebApp.Domain.Core.User", "Author")
                        .WithMany("UserPetitions")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("WebApp.Domain.Core.PetitionUser", b =>
                {
                    b.HasOne("WebApp.Domain.Core.Petition", "Petition")
                        .WithMany("Voters")
                        .HasForeignKey("PetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Domain.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Domain.Core.Poll", b =>
                {
                    b.HasOne("WebApp.Domain.Core.User", "Author")
                        .WithMany("UserPolls")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("WebApp.Domain.Core.VotingOption", b =>
                {
                    b.HasOne("WebApp.Domain.Core.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApp.Domain.Core.VotingOptionUser", b =>
                {
                    b.HasOne("WebApp.Domain.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Domain.Core.VotingOption", "VotingOption")
                        .WithMany("Voters")
                        .HasForeignKey("VotingOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
